/** Rutas canónicas — alinear texto de navegación y URL (SEO) */
export const routes = {
  home: "/",
  catalog: "/catalogo",
  catalogAllProducts: "/catalogo/productos",
  category: (slug: string) => `/catalogo/${slug}`,
  product: (slug: string) => `/producto/${slug}`,
  search: "/buscar",
  quote: "/cotizacion",
  wholesale: "/mayoreo",
  about: "/nosotros",
  services: "/servicios",
  serviceDetail: (slug: string) => `/servicios/${slug}`,
  admin: {
    root: "/admin",
    sliders: "/admin/sliders",
    sliderNew: "/admin/sliders/nuevo",
    sliderEdit: (id: string) => `/admin/sliders/${id}`,
    categories: "/admin/categorias",
    categoryNew: "/admin/categorias/nuevo",
    categoryEdit: (id: string) => `/admin/categorias/${id}`,
    products: "/admin/productos",
    productNew: "/admin/productos/nuevo",
    productEdit: (id: string) => `/admin/productos/${id}`,
    quotes: "/admin/cotizaciones",
    wholesale: "/admin/mayoreo",
    services: "/admin/servicios",
    serviceNew: "/admin/servicios/nuevo",
    serviceEdit: (id: string) => `/admin/servicios/${id}`,
    siteContact: "/admin/sitio",
  },
} as const;
